apiVersion: v1
kind: Service
metadata:
  name: deployment-tracker-service
  namespace: default
  labels:
    app: deployment-tracker
spec:
  type: NodePort
  selector:
    app: deployment-tracker
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30001
